name: CrazyWarps
version: ${project.version}
main: me.ryder.crazywarps.CrazyWarps
api-version: 1.13
authors: [Ryder]
description: A plugin that categorizes warps.
commands:
  cw:
    description: opens up a list of commands
    usage: /cw
  cw reload:
    description: reloads the plugin
    usage: /cw reload
